### ISSUE TITLE
New monument form error messages

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#100]
## Monument Metadata

- [x] **Section:** `Section must be a whole number from 1 to 36.`
- [x] **Corner:** `Corner is a required field.`
- [x] **Monument Status:** `Status is a required field.`
- [x] **Accuracy:** `Accuracy is a required field.`
- [x] **Monument Description:** `Description is a required field.`
- [x] **General Notes:** `Notes is a required field.`

## Step 1: Location Information - Coordinate System
- [x] **Coordinate System:**(drop-down) `Coordinate System is a required field.`

## (Geographic) Step 2: Location Information - Latitude
- [x] **Degrees:** `Degrees must be a whole number from 37 to 42.`
- [x] **Minutes:** `Minutes must be a whole number from 0 to 59.`
- [x] **Seconds:** `Seconds must be a number from 0 to 59.99999.`

## (Geographic) Step 3: Location Information - Longitude
- [x] **Degrees:** `Degrees must be a whole number from 109 to 114.`
- [x] **Minutes:** `Minutes must be a whole number from 0 to 59.`
- [x] **Seconds:** `Seconds must be a number from 0 to 59.99999.`

## (Geographic) Step 4: Location Information - Ellipsoid Height
- [x] **Ellipsoid Height (Meters):** `Ellipsoid Height (meters) must be a number from 600 to 4300.`
- [x] **Ellipsoid Height (Feet):** `Ellipsoid Height (feet) must be a number from 2000 to 14000.`

## (Grid) Step 2: Location Information - Zone and Units
- [x] **State Plane Zone:** `State Plane Zone is a required field.`
- [x] **Horizontal units:** `Horizontal units is a required field.`

### For all three zones, and when horizonal units = meters:
- [x] **Northing:** `Northing value must contain seven values to the left of the decimal, and up to three to the right.`
- [x] **Easting:** `Easting value must contain six values to the left of the decimal, and up to three to the right.`
### For all three zones, and when horizonal units = feet:
- [x] **Northing:** `Northing value must contain eight values to the left of the decimal, and up to three to the right.`
- [x] **Easting:** `Easting value must contain seven values to the left of the decimal, and up to three to the right.`

## (Grid) Step 4: Elevation
- ~[x] **Vertical datum:** `Vertical datum is a required field.`~
### For all three zones, and when horizonal units = meters:
- [x] **Elevation:** `Elevation (meters) must be a number from 600 to 4300.`
### For all three zones, and when horizonal units = feet:
- [x] **Elevation:** `Elevation (feet) must be a number from 2000 to 14000.`

## Monument Images
- [x] **Map View or Sketch:** `Denied. Accepted file types: jpeg, jpg, png, tiff.`
- [x] **Monument Area:** `Denied. Accepted file types: jpeg, jpg, png, tiff.`
- [x] **Monument Close-up:** `Denied. Accepted file types: jpeg, jpg, png, tiff.`
- [x] **Extra Pages:** `Denied. Accepted file types: jpeg, jpg, pdf, png, tiff.`

**Comment by nathankota** [comment]
The messages have been updated for each section of the new monument import workflow, based on discussion with and feedback from Sean.

**Comment by steveoh** [comment]
I thought this was optional 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/325813/200626685-e8cfc6e3-c1d0-45c1-bd36-e074199d16f9.png">

**Comment by nathankota** [comment]
Huh...I thought I crossed out vertical datum yesterday, but must not have saved it, darn it

**Comment by nathankota** [comment]
I'm calling this one validated. Created a few new issues to deal with some little pieces:
#140 
#141 
#142
