### ISSUE TITLE
Only allow NGS 2011

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#103]
@seanfernandez: Do we even need to present a drop-down for this, or just permanently populate the respective fields (below) with "NGS 2011"? 

This is found on the Ellipsoid Height selection for submitted geographic coordinates:
![image](https://user-images.githubusercontent.com/15659642/193415838-bad47449-0540-4928-9d40-3154b1633fc2.png)

And the Zone and Units section for grid coordinates:
![image](https://user-images.githubusercontent.com/15659642/193415874-f866c6f5-3166-4942-9a98-1b7e1ccdb77f.png)

**Comment by seanfernandez** [comment]
Remove NGS Adjustment completely for Ellipsoidal height. 
Only allow NGS 2011 for State Plane. It can either remain in the dropdown as the only option or just be permanently added to the results.

**Comment by steveoh** [comment]
I suggest we add (NGS 2011) next to the ellipsoid height label so they know the format to enter. The single item dropdown is a bit of a UX mistake.

**Comment by seanfernandez** [comment]
actually it was a mistake to have NGS 2011 as an option for ellipsoid height in the first place (my fault).The ellipsoid height for NAD83 is based on a mathematical ellipse called GRS80, which is for all intents and purposes the same as WGS84, so an NGS adjustment is never applied to the vertical for ellipsoid height.
With that said, please remove any adjustment option or reference to and adjustment for ellipsoid height.

**Comment by nathankota** [comment]
I'll break this into some new issues
