### ISSUE TITLE
Auto-calc and display other coordinates during submission

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#105]
## The rules

 - if submitter edits any of the (editable) calculated fields it does not change the originally-entered coordinates
 - if submitter backs out and alters originally-entered coords or changes the coordinate type and enters data, auto-calc wins at the `Next` button click

## When Geographic Coordinates are entered by user

1. Submitter selects `Geographic' and NAD83 and completes steps 2-4
1. Click `Next` (auto-calc activated here)
1. Convert DMS to decimal degrees using [npm dms-conversion package](https://www.npmjs.com/package/dms-conversion)
1. Find intersected county 
1.  Project the geographic coordinates
	- Input spatial reference is always `6318`
	- Output spatial reference is WKID (meters), depending on the county (see below)
	-  x, y in decimal degrees as Geometries input
1. Calculated grid coordinates are displayed on a new page/pane: 
   - (editable) **State plane zone:** according to output spatial reference
   - (editable) **Horizontal units:** default to meters
   - (editable) **Northing:** according to the [Project service](https://mapserv.utah.gov/arcgis/rest/services/Geometry/GeometryServer/project) result
   - (editable) **Easting:** according to the [Project service](https://mapserv.utah.gov/arcgis/rest/services/Geometry/GeometryServer/project) result
   - (editable) **Vertical datum:** defaults to NAVD88
   - (editable) **Elevation:** Blank, but a value can be keyed-in

## When Grid Coordinates are entered by user

1. Submitter selects `Grid` and NAD83 State Plane and completes the next page (steps 2-4)
1. Click `Next` (auto-calc activated here)
1.  Project the grid coordinates
	- Input spatial reference (see WKIDs below) according to 
	    - Selected State Plane Zone value in app (North, Central, South), **and**
	    - Selected Horizontal units in app (meters or international feet)
	- Output spatial reference is always `6318`
	- Easting (x) and Northing (y) as Geometries input
1. Convert resulting decimal degrees from results to DMS using [npm dms-conversion package](https://www.npmjs.com/package/dms-conversion)
1. Calculated Geographic coordinates are displayed on a new page/pane:
	- (editable) **Latitude:** DMS
	- (editable) **Longitude:** DMS
	- (editable) **Ellipsoidal height:** Blank, but a value can be keyed-in

### Test Data

State Plane | Zone | Unit | Degrees Minutes Seconds | Decimal Degrees
----|----|----|----|----
471992.726, 1155931.412 | North | Meters | 41 44 13.04711, 111 50 11.99467 | -111.83666519,  41.73695753
471227.703, 2152950.135 | Central | Meters |  39 42 37.97271, 111 50 08.00858  |  -111.83555794, 39.71054798
448447.811, 3106793.746 | South | Meters | 37 37 38.88675, 112 05 02.49362  | -112.0840260048357, 37.62746854366249

### State Plane Coordinate Zones, WKIDs, and Counties

Zone | Meters | Int'l ft | Counties in Zone
---|---|---|---
North | 6620 | 103166 | Box Elder, Cache, Daggett, Davis, Morgan, Rich, Summit, Weber
Central | 6619 | 103167 | Carbon, Duchesne, Emery, Grand, Juab, Millard, Salt Lake, Sanpete, Sevier, Tooele, Uintah, Utah, Wasatch
South | 6621 | 103168 | Beaver, Garfield, Iron, Kane, Piute, San Juan, Washington, Wayne

**Comment by seanfernandez** [comment]
Provide SPC and Geographic Lat Long for 3 common points, one in each state plane zone.
Investigate the NGS conversion tools.
https://www.ngs.noaa.gov/web_services/ncat/lat-long-height-service.shtml

**Comment by nathankota** [comment]
from @seanfernandez:

> https://drive.google.com/drive/folders/1mLmjz_Z962ChnQRdADpdMrjP-qNJhzot?usp=sharing
> This folder contains a spreadsheet with the counties listed by state plane zone and contains a file with coordinates of a point in each state plane zone.
> https://www.ngs.noaa.gov/web_services/ncat/index.shtml
> This link is to the NGS coordinate conversion tool API and can possibly be used to perform our conversions.

**Comment by nathankota** [comment]
## When Geographic Coordinates are entered by user
- Convert DMS to decimal degrees using [npm dms-conversion package](https://www.npmjs.com/package/dms-conversion)
- Find intersected county 

**In the [mapserv Project service](https://mapserv.utah.gov/arcgis/rest/services/Geometry/GeometryServer/project):**
- Input spatial reference is always `6318`
- Output spatial reference is WKID (meters), depending on the county (see below)
-  x, y in decimal degrees as Geometries input

## When Grid Coordinates are entered by user

**In the [mapserv Project service](https://mapserv.utah.gov/arcgis/rest/services/Geometry/GeometryServer/project):**
- Input spatial reference (see WKIDs below) according to 
    - Selected State Plane Zone value in app (North, Central, South), **and**
    - Selected Horizontal units in app (meters or international feet)
- Output spatial reference is always `6318`
- Easting (x) and Northing (y) as Geometries input

**Then:**
- Convert decimal degrees from results to DMS using [npm dms-conversion package](https://www.npmjs.com/package/dms-conversion)

## And finally...
- Display calculated values on the next page in the app (#91)

---
### Reference: State Plane Coordinate Zones, WKIDs, and Counties

**Zone:** North
**WKID (meters):** `6620`
**WKID (Int'l ft)**: `103166`
**Counties:** `[Box Elder, Cache, Daggett, Davis, Morgan, Rich, Summit, Weber]`

**Zone:** Central
**WKID (meters):** `6619`
**WKID (Int'l ft)**: `103167`
**Counties:** `[Carbon, Duchesne, Emery, Grand, Juab, Millard, Salt Lake, Sanpete, Sevier, Tooele, Uintah, Utah, Wasatch]`
 
**Zone:** South
**WKID (meters):** `6621`
**WKID (Int'l ft)**: `103168`
**Counties:** `[Beaver, Garfield, Iron, Kane, Piute, San Juan, Washington, Wayne]`

**Comment by nathankota** [comment]
## Test coordinates

### State Plane (North Zone)
**EASTING (X):** 471992.726 m
**NORTHING (Y):** 1155931.412 m
### Analgous Geographic Coordinates
**DD (x):** -111.83666519
**DD (y):** 41.73695753
**DMS (lat):** 41 44 13.04711
**DMS (W long):** 111 50 11.99467

### State Plane (Central Zone)
**EASTING (X):** 471227.703 m
**NORTHING (Y):** 2152950.135 m
### Analgous Geographic Coordinates
**DD (x):** 
**DD (y):** 
**DMS (lat):** 39 42 37.97271
**DMS (W long):** 111 50 08.00858  
 
### State Plane (South Zone)
**EASTING (X):** 448447.811 m
**NORTHING (Y):** 3106793.746 m
### Analgous Geographic Coordinates
**DD (x):** 
**DD (y):** 
**DMS (lat):** 37 37 38.88675
**DMS (W long):** 112 05 02.49362

**Comment by nathankota** [comment]
I still need to calc the expected decimal degrees outputs for the Central and South zone geographic analogs.

**Comment by steveoh** [comment]
This is currently working but is not polished. 

I do not know what happens if the projection service takes too long or the points are invalid. Those error cases need to be addressed.

**Comment by nathankota** [comment]
I'm going to call this validated and we can deal with any future needs with new issues. #137 should help eliminate most potential error cases, without the implementation of an enhancement to show/zoom to the location of the entered point. I will also create a new issue for projection service taking too long.
