### ISSUE TITLE
Allow pdf file upload

### ISSUE THREAD

**Issue by steveoh** [agrc/plss#109]
For logged in users, enable upload of a pdf file containing their existing tie sheet (required) when they choose to upload an existing sheet

**Comment by nathankota** [comment]
Validated as it currently works. It will be further confirmed when the Uploaded Tiesheet function is wired up to access/preview/download the uploaded sheet. (do you want a task/issue for that @steveoh)
![image](https://user-images.githubusercontent.com/15659642/201740335-eb010454-6e12-4f38-b14b-b4a5a8e3fbaa.png)

**Comment by steveoh** [comment]
If there is not already a task then yes.
