### ISSUE TITLE
Draw attention to Home icon when page loads

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#110]
@steveoh recommended:

> https://react-joyride.com/custom seems like a solution but I wouldn't want to bring in the whole library for one interaction. We could certainly take a hint from their work and create some attention grabbing animation?

I like the idea of a blinking dot/point/arrow with some text to draw in the user's attention to the Home icon. I don't think the animation itself needs to be clickable like the react component, since the Home icon is what we want them to click on. There should, however, be some way to quickly and easily "ignore" or shut off the animation. 

![image](https://user-images.githubusercontent.com/15659642/196465193-a9c354c1-c4ce-465e-bc0a-40d4ddbf9c38.png)

**Comment by steveoh** [comment]
I will need to refactor the form to better handle the existing and new data entries that will share the coordinate entry. When I do this the Home Screen can be open by default making this unnecessary right?

**Comment by nathankota** [comment]
> I will need to refactor the form to better handle the existing and new data entries that will share the coordinate entry. When I do this the Home Screen can be open by default making this unnecessary right?

Yes, if a refactor will enable the Home screen to open by default, this is unnecessary. Would you like for me to 
- [ ] edit this issue to capture the idea of opening Home by default 
- [ ] close this and add a new issue for opening Home by default 
- [ ] close this and not track the open Home by default idea

**Comment by steveoh** [comment]
[x] other. leave it all open until i can refactor and see if you approve.

**Comment by nathankota** [comment]
opening Home by default is the solution. 👍
