### ISSUE TITLE
Choose File changes to Remove after Monument images/files uploaded

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#115]
On the new sheet pathway, Monument Images page, once a file is successfully uploaded, the `Choose File` button changes to a `Remove` button which, when clicked
- Asks the user to confirm that they want to remove the file (yes/no)
- Resets the Remove File button back to Choose File
- Deletes the uploaded file
- Clears the file name and image preview from the UI

![image](https://user-images.githubusercontent.com/15659642/200438225-26128cf2-f387-4a2f-85ff-e76ef690be57.png)

**Comment by steveoh** [comment]
When the permission is denied, i think it's common to simply choose a different ideally correct file. I do like the idea of a remove button since we store the image no matter what. I store the file with the same  name so it overwrites anything prior.

**Comment by nathankota** [comment]
> When the permission is denied, i think it's common to simply choose a different ideally correct file. I do like the idea of a remove button since we store the image no matter what. I store the file with the same name so it overwrites anything prior.

I'm on board with your preference for the denied file. 
I noticed that choosing a correct or different file will overwrite, which is great. Also thinking of the situation where someone uploaded to the wrong section and wants to clear it. Your `Remove` button would handle that.

**Comment by nathankota** [comment]
This works as intended. New issues/tasks will be created to address other related items.
