### ISSUE TITLE
Add another category to the Map Layer Legend

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#116]
- **Name:** MRRC Monument Record
- **Color:** Light blue
- Include question mark icon 

Something along the lines of:

![image](https://user-images.githubusercontent.com/15659642/196555504-acb845f8-7167-43c9-934b-cf53f1804375.png)

**Comment by steveoh** [comment]
We do not have and pending points in the plss points map. How are those determined?

**Comment by nathankota** [comment]
This looks great. We will deal with the question about Pending in #127
