### ISSUE TITLE
Allow uploaded files to persist

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#117]
On Monument Images page:

### Current behavior
- Click `Choose File`
- Select an acceptable file type (e.g. png)
- Preview of the image appears
- Click `Back` or `Next` at bottom of page
- Go back to Monument Images page
- Monument Images page is reset

### Expected behavior
- Click `Choose File`
- Select an acceptable file type (e.g. png)
- Preview of the image appears
- Click `Back` or `Next` at bottom of page
- Go back to Monument Images page
- The preview and name of the added file should persist on the page, as long as the Clear button had not been clicked before navigating away from the Monument Images page (#115). Any denied files' information can disappear.

**Comment by steveoh** [comment]
I don't like the idea of persisting an invalid value in a file upload if the next or back button is clicked.

**Comment by nathankota** [comment]
> I don't like the idea of persisting an invalid value in a file upload if the next or back button is clicked.

I agree. Original comment has been edited to address this.

**Comment by steveoh** [comment]
This is partially complete. But please check it out and comment about the direction.

**Comment by nathankota** [comment]
I did not experience this working as expected. 
- Uploaded different jpg files in the first two sections, clicked Back, then Next, and the images were not visible. Uploaded again, clicked Next, then Back, and images were gone
- As I attempted more uploads the previews were not available:
![image](https://user-images.githubusercontent.com/15659642/199801130-1133de37-6de2-42c5-8b71-57fec25fbb32.png)

**Comment by steveoh** [comment]
I should have mentioned that my first crack at this is only in the existing submission path

**Comment by nathankota** [comment]
> I should have mentioned that my first crack at this is only in the existing submission path

If this is still the case, then it looks like it is working for existing sheets b/c I can choose a pdf, advance to the next page, go back, and the Remove button is still there, indicating that a file has been uploaded. (#152 will be helpful to know for sure)

If this has been implemented for the new sheet path, then it is not working as expected. Uploading an image produces the image preview, but going Back then advancing again to the Monument Images page, the image previews are gone. I am unable to test uploading monument images then going forward, then back to the page, due to #150.

**Comment by steveoh** [comment]
You might need to show this to me. And remember that form data is only saved when advancing in the wizard.

**Comment by nathankota** [comment]
> You might need to show this to me. And remember that form data is only saved when advancing in the wizard.

Thanks for the clarification. I was testing based on my original comment to allow files to persist when either Next _**or**_ Back was clicked, but I understand the need to save form data when advancing only. I was eventually able to experience the app advancing to the submit page, despite #150, then go back to Monument Images and the uploaded previews persisted, so I am going to call this one validate 👍

**Comment by steveoh** [comment]
It's an interesting expectation to save your data on back. We _could_ do that. 

I might lean towards popping a notification when the form is dirty that you will lose the changes. 

That exposes an edge case with uploads since all uploads overwrite prior uploads regardless of whether you click next or back. The behavior is different than the form inputs because the uploads don't sit in a text input waiting for the next button. When the form advances it saves the path to the file if it has one. So you could choose a file, back up, and not see a preview when you go forward but the file will still be in storage. 

I'm not sure what the best approach here is.
