### ISSUE TITLE
Add button/icon for My Location

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#118]
Add a (crosshair-type) icon on the map that allows the app to zoom to and show a point at the user's location for both desktop and mobile.

> The blue dot is just that, a blue dot on the map showing your current location. This will be very useful for surveyors using the mobile app to see where they are in the field relative to a section corner.

**Comment by nathankota** [comment]
On a mobile device it does well to find my actual location. On a laptop it places me about 1 mile from my location.

I couldn't figure out how to replicate this, although it happened once or twice on mobile, and a few times on desktop during 30 minutes or so of testing, but it irregularly stops working and the tool will spin for a few seconds: 

![image](https://user-images.githubusercontent.com/15659642/208782922-ed82031a-8cd7-4fb3-8ba5-8b8a544ca050.png)

Then turns red and is unusable unless the page is refreshed. On laptop it happened a few times where it would turn red immediately and be unusable, even after a page refresh. But it didn't seem to be happening consistently.

![image](https://user-images.githubusercontent.com/15659642/208781129-c1473ea1-5ba2-414c-bcc2-7e63d78c0918.png)

I also like the track mode when it is turned on, although probably more useful for mobile users. 
![image](https://user-images.githubusercontent.com/15659642/208781225-c3c4f5ab-029a-4ea0-a832-53e9f84adb66.png)

**Comment by steveoh** [comment]
Laptop geolocation is based on your ISP so 1 mile away is normal unless it's not consistent. The browser is in charge of returning coordinates and we can't do anything there.

If it turns red, that means an error occurred getting your location. This is typically permission/privacy based or you exceeded a 5 second timeout of having your browser give you a location. 

It will turn grey if your browser does not support the geolocation api.

**Comment by nathankota** [comment]
I'm satisfied with how it works. I'll let Sean know it's available and to test it out to see if it suits his desired functionality, as it was a high priority for him. Otherwise, I'm going to close this.
