### ISSUE TITLE
Show list of links to all approved tie sheets for a PLSS point

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#119]
When user clicks `Tie Sheet Document(s)` show a list of links to access/open each tie sheet approved for a selected point 

> there is a new requirement to store multiple tie sheets for a point, as improved data/sheets are collected over time

![image](https://user-images.githubusercontent.com/15659642/196802349-5f1aa5fc-3dc4-45b4-a132-1e4b1463982e.png)

**Comment by steveoh** [comment]
Where will that data come from?

**Comment by nathankota** [comment]
Your direction/recommendation will be highly valued on this. My initial question is whether the first step should be to move the existing sheets (1 per point, for those point that have them) to a bucket or other cloud storage, rather than their current location; and wire up the app to replicate the the tie sheet view that exists in the current app, with an eye on there being multiple sheets per point in the future.

**Comment by steveoh** [comment]
Ok. I'll think about it. I wanted to make sure that I was correct in thinking that this wasn't currently possible.

**Comment by nathankota** [comment]
"Fake it" for some MRRC Monument Record points (#116)

**Comment by nathankota** [comment]
This is awesome. For reference, there are some MRRC points with multiple tie sheets slightly southwest of Grantsville.
