### ISSUE TITLE
Large file submissions failing

### ISSUE THREAD

**Issue by steveoh** [agrc/plss#12]
Some requests are too large and are failing. Handle this gracefully.

Some requests are failing because the framework thinks a request is dangerous. The request has an & in the content. This is illegal and should be encoded. Do the encoding.

**Comment by mheagin** [comment]
I talked to Kate and she didn't remember seeing any "&" in any of the names. 2 everything she was loading is under 1 MB. She tried again this morning and got the same results.
I did go in and clear out old data, pre 2017 just to make room, does not seem like that made a difference.
Can you take a look at the logs for this morning when you get a chance. Thanks

**Comment by steveoh** [comment]
Will you get an exact copy of the text and documents she is submitting so we can reproduce internally.

**Comment by mheagin** [comment]
Hey I got the files and tried got the same error she sent us.
But the files were 12.5 MB so too big.
They are going to use the pdf optimizer and make them smaller.
Will fix the issue for them. You can close this bug out.
