### ISSUE TITLE
Mirror PLSS data storage from old to new server

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#121]
**INC1735503** for moving the monument records

Move data from `Data (d:)/PLSS` on grgisweb1 to itwgisweb1gp to make sure anything submitted to the existing plss app between March 2022 (when the first mirror was done) and October 11, 2022 (when PLSS app was switched to the gcve server storage) is not left behind.

**Comment by nathankota** [comment]
...and get Mike and Erik access to the new data store

**Comment by steveoh** [comment]
Do you have everything you need to create the SN inc for this?

**Comment by nathankota** [comment]
> Do you have everything you need to create the SN inc for this?

If you have a sec today to chat through the details of the request, that would be greatly appreciated.

**Comment by steveoh** [comment]
I'll create the issue

**Comment by nathankota** [comment]
INC1735503

**Comment by nathankota** [comment]
This part is complete. #124 for the access piece.
