### ISSUE TITLE
Change Horizontal units title and feet selection

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#123]
#### Change data field title:
From: `Horizontal units`
To: `Units`

![image](https://user-images.githubusercontent.com/15659642/198150354-e5f46540-221b-47de-a069-a6310ee4f225.png)

#### Change feet units selection:
From: `Feet`
To: `International Feet`

![image](https://user-images.githubusercontent.com/15659642/198151016-e63e5392-a737-4650-9df6-5668a1424f2b.png)

**Comment by steveoh** [comment]
Ok, make up your mind. https://github.com/agrc/plss/issues/104

**Comment by nathankota** [comment]
I know...busted!

**Comment by nathankota** [comment]
validated
