### ISSUE TITLE
Add X to clear point, panel, and submission data

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#126]
Ref: #102 

- Add a fairly prominent `X` icon in the top, right corner of the identify panel, and all subsequent submission pages/panels.
- When `X` is clicked while on the identify panel, it acts the same as the `Close` button should, to close the panel and deselect the point.
- When `X` is clicked while on any of the submission pages, it clears any data that has been entered thus far, closes the panel, and deselects the point.
- The map remains at the same location and zoom level as when the point was clicked/selected.

**Comment by steveoh** [comment]
I still need to reset the state machine...
