### ISSUE TITLE
Values remain in drop down form fields after Clear button clicked

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#128]
When entering data for a new sheet, then clicking `Clear`, the app recognized the fields as not containing data because it kicks the error messages for those fields if you try to advance, but the previously-entered values still remain in the form UI. 

Also, if you enter data (e.g. Latitude), click Clear, go back, then forward again to Latitude, the values are still there.

This only appears to be an issue for drop-down data fields, for example:

### Monument Metadata page
- Section Corner, Monument Status, and Accuracy values remain after clicking `Clear`:
![image](https://user-images.githubusercontent.com/15659642/199772678-90c9da48-a0a7-41fe-bcc4-371a39edadb5.png)

### Location Information - Coordinate System
 - Select NAD83 for either Geographic or Gird, click `Clear,` and previous value remains in the UI
![image](https://user-images.githubusercontent.com/15659642/199773898-b7755e4f-57ae-432a-bdf7-1d88cb5e3517.png)

**Comment by nathankota** [comment]
It works to clear the values now, but they (the values) return after going back and advancing again. For example,
- Set coordinate system to Geographic, NAD83 Geographic, click Next
- Enter Latitude DMS, click Next
- Enter Longitude DMS
- Click Clear
- Back to Latitude and Clear
- Back to Coord System page
- Next to Latitude, and the previously entered and cleared values appear
- Next to Longitude, and the previously entered and cleared values appear

I'm not really sure about how much time to spend chasing this while there is quite a bit still to do for the MVP release. Should we make a new issue for this and have it as a post-release enhancement?

**Comment by steveoh** [comment]
Wait, we don't save the values when going back, only foward

**Comment by nathankota** [comment]
> Wait, we don't save the values when going back, only forward

I thought that was the case, which made it seem even odder that the values were reappearing

**Comment by nathankota** [comment]
Disregard comments above. This is working as it should, since clicking Next will save the entered value(s). Then if you go back and clear values, continue to go back once more, then forward again, it will reinstate the previous values that were saved when Next was initially clicked.
