### ISSUE TITLE
Clear button doesn't work on Vertical datum

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#129]
- Grid coordinate entry
- Location Information, step 4: Elevation
- Select NAVD88 or NGVD29 for the Vertical datum
- Click `Clear`
- Vertical datum field stays populated and the app recognizes the value (as opposed to #128)

**Comment by steveoh** [comment]
i think this is also fixed by #2ba50ed

**Comment by nathankota** [comment]
validated
