### ISSUE TITLE
Default to https

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#13]
I took a look at the PLSS app http://mapserv.utah.gov/PLSS/
When first open the web site is public. View-able only no need to secure.
If you log in it is just a drop down not secure, so login and pass not protected.
Once logged in it is still not a secure site no https, nothing secured.
To get login need to be approved by Steve / Sean I believe 
then you can submit corner, these should be approved by County rep. But might not always be the case.
Can we make this a secure site when creating a login or when you login.
Not sure if we need to be secure for just general browsing.
Thanks

**Comment by steveoh** [comment]
Use https://mapserv.utah.gov/plss

**Comment by steveoh** [comment]
I will look into redirecting to https always

**Comment by steveoh** [comment]
i have an open incident to force https and the app now has no mixed content warnings. I'll close this after the service now issue is closed.
