### ISSUE TITLE
Add Back button on first page of new sheet submission

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#130]
- Add `Back` button to the left of the `Clear` button on the first page of the new sheet submission
- When `Back` is clicked
    - Return to identify page
    - If user selects the new sheet pathway again, any data they already uploaded or entered remains
    - If user selects the existing sheet submission path, any previously-entered data in the new sheet path is reset/removed/deleted

![image](https://user-images.githubusercontent.com/15659642/200436594-aba71bfb-e300-4746-b150-d6c41cff1550.png)

**Comment by steveoh** [comment]
It seems odd to have different form data retention if the back button is chosen depending on the route you choose.

**Comment by nathankota** [comment]
I initially thought it would be helpful for data to be retained if they backed out, then chose again the path they were on previously. However, I prefer the simplicity of resetting the state machine when new or existing is clicked.

> Are implying that any existing sheet uploads should be deleted?
Yes, to deal with orphaned files. This will need a new issue anyway. I've been thinking about the scenarios of when it should happen. 

Otherwise, I believe this is validated as it works now.
