### ISSUE TITLE
Upload existing sheet allows jpg, png

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#131]
Should only allow pdf (#109)

![image](https://user-images.githubusercontent.com/15659642/199833037-d77dac0f-38d4-4f7d-8761-1a8c8a563f8b.png)

**Comment by steveoh** [comment]
Can't reproduce. 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/325813/202537633-48dfe2de-a96a-46d8-be91-6179ca9658e5.png">
