### ISSUE TITLE
Make file upload error message disappear

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#135]
When an incorrect file type upload is attempted, the file name should not appear under the `Choose File` button, and the upload error message should disappear after a few seconds. This affects the two places where file upload can occur, 1) New sheet > Monument Images and 2) Existing sheet > Monument Sheet 

E.g. 

![image](https://user-images.githubusercontent.com/15659642/200441878-6c6a624c-3740-488a-a995-183876d9f7b3.png)

**Comment by steveoh** [comment]
I'm not sure I agree with this. I would argue that the message should persist as long as the chosen file is of the wrong type. The message goes away when choosing the correct file type after trying again.

**Comment by nathankota** [comment]
> I'm not sure I agree with this. I would argue that the message should persist as long as the chosen file is of the wrong type. The message goes away when choosing the correct file type after trying again.

I agree that this is an appropriate way to deal with it. Validated.
