### ISSUE TITLE
Acceptable values for state plane

### ISSUE THREAD

**Issue by steveoh** [agrc/plss#137]
I put in some poor values for state plane coordinates that were projected to values outside of utah that did not pass validation. 

Please provide, for each zone, the min and max range of coordinates in feet and meters.

**Comment by nathankota** [comment]
We talked about this last week @seanfernandez. I dinged Mike to see if he could help out. Let's set up a time to figure this out today or tomorrow.

**Comment by nathankota** [comment]
Finish this from: https://docs.google.com/spreadsheets/d/1XIPiaUKgtkV3I7tt0KqAKdNmyCxHsicssJ4YJriWjCA/edit#gid=0

**Comment by nathankota** [comment]
Zone | Coordinate | Range (meters) | Range (int'l ft) 
----|----|----|----
North | northing | 1023805 - 1187493 | 3358936 - 3895966
North | easting | 286163 - 707394  |  938853 - 2320842
Central | northing | 2018522 - 2305365 | 6622436 - 7563519
Central | easting | 277782 - 712847 | 911357 - 2338732
South | northing | 3037239 - 3214610 | 9964678 - 10546599
South | easting | 273034 - 718496 | 3037239 - 3214610

**Comment by nathankota** [comment]
validated!
