### ISSUE TITLE
Looking for a "you are here" icon for mobile user

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#14]
We would like to know if there is a way to provide an location Icon for folks using the app in the field. Based on their gps on their phone. Sean has had several discussions with surveyors that would like to use the app while they are working in the filed to locate the corner markers. having a location icon that moves with you would be ideal. 
Is this something we can do with the current app or is it something where we need to modify the app so it is more of a mobile design and functionality. 
Let us know or it you want to sit down and talk we are around.

**Comment by steveoh** [comment]
This is definitely possible and also depends on #13 since geolocation requires https.

**Comment by steveoh** [comment]
closed by b5bbe724dae2d23824d1422b6057619d115d6b07
