### ISSUE TITLE
Preview tiesheet before submission

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#143]
On the Corner Submission Review page, keep all the review elements, and enable a preview of the tiesheet as it would look according to the data entered through the wizard; while keeping the Submit button prominent so user does not forget to click it.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

**Comment by steveoh** [comment]
I worry a bit that if someone downloads the preview they may be distracted and not finish the submission.

**Comment by nathankota** [comment]
Sean is concerned about this too. He wondered about the possibility of having the Submit button somehow embedded in the preview.
> I worry a bit that if someone downloads the preview they may be distracted and not finish the submission.

**Comment by nathankota** [comment]
Initial comment edited. @steveoh does the updated issue description address [your comments above](https://github.com/agrc/plss/issues/143#issuecomment-1309551512)?

**Comment by steveoh** [comment]
This is confusing. I think it needs to be read again and updated to match the title with the content.

**Comment by nathankota** [comment]
better?

**Comment by steveoh** [comment]
I think this has issues still. This is the preview pdf. They have not submitted it. That pdf _should_ contain the watermark which will discourage people from only going that far and using the preview to submit to other places. If they want to use the pdf to submit to other places, they should submit the form and download it from their my content area or we should email it to them after it's submitted.

**Comment by nathankota** [comment]
title and description edited again

**Comment by nathankota** [comment]
it's awesome!
