### ISSUE TITLE
Monument Record Sheet layout

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#144]
The layout of the existing sheet is mostly solid, with some requested tweaks. 

- Pdf is preferred (no "form" editing necessary)
- Change name to (centered alignment of each line):
  Monument Record Sheet 
                    for
           (county name)
- Remove logos
- Add a section for `Units` under ellipsoid height in the Geographic Coordinates section (value will be either meters or international feet)
- Change `Horizontal Units` to `Units`
- Change `Ortho Elevation` to `Elevation`
- Remove `NGS Adjustment`
- Remove `Vertical Units` (I think this is now just the "units" fields above)
- Put the Disclaimer in the footer of the page; keep the text red
- Widen the Monument Description box, since the disclaimer removed
- Widen the Additional Notes, also due to disclaimer removal
- Keep the surveyor seal section in the bottom right corner - it can still take up some space from the additional notes
- Additional images - grid of four on two pages, then two on the last page (I think we allow 10?)
- Additional files (pdf) - append them to the monument record sheet

![image](https://user-images.githubusercontent.com/15659642/200968763-ce30d6e6-ba9d-478b-be8b-a7847ec04fe0.png)

**Comment by steveoh** [comment]
Can you mock up the form instead of listing changes from the current please? That should be easier for me to work follow.

**Comment by nathankota** [comment]
The Lucid mockup is [here](https://lucid.app/lucidchart/3aa62443-49eb-45ba-8fc2-c18ddb0a1c7c/edit?viewport_loc=-1163%2C-87%2C4039%2C2017%2C0_0&invitationId=inv_235ada5a-01fc-4612-aed7-9163c18aae0d).

**Comment by steveoh** [comment]
> The Lucid mockup is [here](https://lucid.app/lucidchart/3aa62443-49eb-45ba-8fc2-c18ddb0a1c7c/edit?viewport_loc=-1163%2C-87%2C4039%2C2017%2C0_0&invitationId=inv_235ada5a-01fc-4612-aed7-9163c18aae0d).

Ok, I left a few comments.

**Comment by nathankota** [comment]
The layout looks awesome. Any changes or tweaks will be handled in new tasks/issues.
