### ISSUE TITLE
plss.utah.gov

### ISSUE THREAD

**Issue by steveoh** [agrc/PLSS#15]
set up website with domain

**Comment by seanfernandez** [comment]
From: <registrar@utah.gov>
Date: Mon, Sep 28, 2015 at 12:47 PM
Subject: Approved and Activated Sub-Domain Name
To: sfernandez@utah.gov
Cc: sfernandez@utah.gov
Your new sub-domain name http://plss.utah.gov has been approved, activated and ready for your use.
If ITS will provide DNS services for your sub-domain, you may now add additional hosts/aliases for the approved sub-domain.
For instance, if your site wildride.utah.gov has been approved and activated, you can now go to the registrar website and register fantastic.wildride.utah.gov or www.wildride.utah.gov.
To do this, click on the following link:
http://registrar.utah.gov/registrar/do/forwarder?domainid=act
ADMIN CONTACT PLEASE NOTE: IF ITS IS HOSTING YOUR SITE, IT WILL NOT BE FULLY ACTIVE
UNTIL YOU PROVIDE THE INFORMATION TO THE ABOVE WEB SITE INCLUDING THE IP ADDRESS.

**Comment by steveoh** [comment]
INC0809011
