### ISSUE TITLE
Cannot advance after uploading monument images

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#150]
- New sheet pathway
- Get through the steps in the submission process to arrive at the Monument Images page
- Select `Choose File` and upload an image to one of the sections (map view/sketch, monument area, etc.)
- Image preview appears
- Click `Next`
- App does not advance to the review/submit page
### Expected
- Click `Next`
- App advances to review/submit page

**Comment by nathankota** [comment]
wait a minute...this worked after testing a couple more times.

**Comment by nathankota** [comment]
It eventually worked after removing an image, going back then forward to add a new one, then removing and advancing to the review/submit page, then going back and adding an image, then advancing again to review/submit.

**Comment by steveoh** [comment]
I was not able to reproduce this. These are the values I used.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/325813/202303836-e0a54733-136c-42ee-b89a-a03a6f4451fe.png">

**Comment by steveoh** [comment]
This issue was that i was uploading png's and nathan was uploading jpgs and the schema was wrong. also the error messages were not being displayed. All of that should be fixed now.

**Comment by nathankota** [comment]
Uploaded jpeg and still not able to advance.

**Comment by nathankota** [comment]
Also attempted with a png and not able to advance.

![image](https://user-images.githubusercontent.com/15659642/202502222-97d619bb-d4c0-4eb3-a3c6-3e6e56c8e87e.png)


![image](https://user-images.githubusercontent.com/15659642/202501921-e91fe472-6cf8-42d2-8faa-b86adc59d425.png)

**Comment by steveoh** [comment]
Yah I messed up the expression but the tests pass 😐

**Comment by nathankota** [comment]
I am not experiencing anymore issues with this. Nice work!
