### ISSUE TITLE
Previous image preview persists with new image

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#151]
### New sheet pathway
- Monument Images page
- Upload an image and preview successfully generated
- Click `Remove`
- Image is removed
- `Choose File` and add new image
- Previous image appears in the preview, rather than the new image
### User profile - surveyor seal
- upload and save surveyor seal image
- exit profile, then go back into profile
- click Remove
- click Choose File, and upload new image
- the originally-uploaded image appears in the preview

**Comment by steveoh** [comment]
This highlights that changes are only saved when the next button is clicked.

**Comment by nathankota** [comment]
> This highlights that changes are only saved when the next button is clicked.

Initial comment edited to address this

**Comment by nathankota** [comment]
Nice work!
