### ISSUE TITLE
Show preview of uploaded pdf and any entered coordinates before submission

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#155]
At the end of the existing sheet pathway, on the review page,
- If submitter entered coordinates in the wizard then show them
- Change the `Tiesheet` section text to `Uploaded Tiesheet`
-  Show a preview of the uploaded pdf so submitter can validate that it was what they meant to upload

 
![image](https://user-images.githubusercontent.com/15659642/203186086-7925502c-1871-4cc8-9792-ae2dfe8437d7.png)

**Comment by steveoh** [comment]
What does it currently do?

**Comment by nathankota** [comment]
opens a tab with https://plss.dev.utah.gov/submitters/YpFOzCA1UeaCw2GUPalN1fjl8KC2/existing/UT260420S0110W0_100200/existing-sheet.pdf

**Comment by steveoh** [comment]
I would prefer to keep it the way it is considering people can right click and save as or download or print from the open tab. 

<img width="97" alt="image" src="https://user-images.githubusercontent.com/325813/202581100-f112b726-a755-4708-96f8-e1b4e0b3967b.png">

**Comment by nathankota** [comment]
I like the flexibility too, but it brings up the issue again of someone getting distracted and not finishing their submission:

https://github.com/agrc/plss/issues/143#issuecomment-1309551512

**Comment by steveoh** [comment]
Should we remove the download link? They already have the file downloaded since they just uploaded it. For that reason I don't view this as the same situation as 143.

**Comment by nathankota** [comment]
> Maybe we look into generating a png preview of the pdf and show that rather than the pdf download link.

This, or maybe just show the pdf name so they have visual confirmation that it is the file they meant to upload.

**Comment by nathankota** [comment]
Issue title and initial comment changed.

**Comment by steveoh** [comment]
> This, or maybe just show the pdf name so they have visual confirmation that it is the file they meant to upload.

It's not a good practice to store or display the name of the file the uploaded as it could be malicious.

**Comment by nathankota** [comment]
Title and description altered again. @steveoh is looking into a react component to show the pdf.

**Comment by nathankota** [comment]
Yessssssss!
