### ISSUE TITLE
What happens when the Submit button is clicked?

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#157]
- Message: `Monument Record Submitted` :heavy_check_mark:
- My Content opens, with new record at the top of the Monument Submissions list (#165)
- ...

**Comment by steveoh** [comment]
Didn't we talk about having it go to the `my content` section and show the status?

**Comment by steveoh** [comment]
This discusses what happens on the front end. So far on the back end,

- the data is validated
- the required fields are plucked from the submission and stored in the db

things that need specified still

- we discussed emailing the monument record sheet to the submitter but it's not referenced
- we haven't discussed submission statuses (pending, approved, rejected)
- we haven't discussed internal notifications (cadastre group, etc)
- we haven't discussed external notifications (county surveyors, etc)

**Comment by nathankota** [comment]
> Didn't we talk about having it go to the `my content` section and show the status?

Yes, I'm working on mocking something up for this, and will work on addressing the other things.

**Comment by steveoh** [comment]
@nathankota check out the submission flow right now. The simplest way is to go existing without coordinates.

**Comment by steveoh** [comment]
I'm thinking of determining status from these values

```js
status: {
      ugrc: {
        approved: false,
        approved_data: null,
        rejected: false,
        rejected_date: null,
        received: false,
        received_date: new Date(),
        comments: null,
      },
      county: {
        approved: false,
        approved_data: null,
        rejected: false,
        rejected_date: null,
        received: false,
        received_date: null,
        comments: null,
      },
    },
```

**Comment by nathankota** [comment]
> @nathankota check out the submission flow right now. The simplest way is to go existing without coordinates.

It looks awesome, and Sean approves. I met with him today about statuses and some other things and I will work on a state & transition model tomorrow.

**Comment by nathankota** [comment]
@seanfernandez @steveoh 
Post-submission state/transition diagram is [here](https://lucid.app/lucidchart/68a18afb-1a66-46f8-b32c-3c6e8f3cee99/edit?viewport_loc=-290%2C-20%2C2742%2C1369%2C0_0&invitationId=inv_a64a4ac1-84b7-4442-a0dc-0dffe56d4348), and will need a review.

**Comment by steveoh** [comment]
should we close this and open new issues for the back end stuff since this is targeting the front end and that is mostly done?

**Comment by nathankota** [comment]
> should we close this and open new issues for the back end stuff since this is targeting the front end and that is mostly done?

_lez do it_
