### ISSUE TITLE
Move zoom tool to top right of map

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#158]
The zoom tool is obscured by the left panel when it is open. Move zoom tool to the top right corner so it is always visible.

![image](https://user-images.githubusercontent.com/15659642/202580989-e70fbeb9-6e09-485f-899b-32e0bfa6f850.png)

**Comment by steveoh** [comment]
This is only an issue in the desktop view. My vote would be to move the buttons to the top right.

**Comment by nathankota** [comment]
> This is only an issue in the desktop view. My vote would be to move the buttons to the top right.

Agreed. Issue title and initial comment edited to reflect this. Do we want or need to consider adhering to the [DTS design system](https://agrc.slack.com/archives/C0J15U8G6/p1668723839177269) for this?

**Comment by steveoh** [comment]
I moved this to the bottom right like google maps.

**Comment by nathankota** [comment]
It does look a little funky on mobile, and is hidden when the panels are open:

![image](https://user-images.githubusercontent.com/15659642/208546831-d9fda9e9-8afa-4376-a156-c53b6f2777cd.png)

![image](https://user-images.githubusercontent.com/15659642/208546952-ea780be1-9327-4330-a211-03fa043332ed.png)

**Comment by steveoh** [comment]
Yeah the view padding is fouling it up. I need to update the view padding to change with the drawer being open and closed. I think on large vs small screen i'll put the tools in tisible places

**Comment by steveoh** [comment]
I've made some changes here. This is ready for another look.

**Comment by nathankota** [comment]
This looks good to me. To summarize the following tool locations now prevent them from being obstructed by the menus panel.
**Desktop:** Zoom and "my location" tools are bottom right
**Mobile:** Zoom and "my location" tools are upper left
