### ISSUE TITLE
Monument record sheet - a couple elements missing and a change

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#162]
## Change
- Put the `Accuracy` data at the top of the Monument Description, followed by a carriage return, then the entered text starting on the next line
![image](https://user-images.githubusercontent.com/15659642/203440278-e2e28091-582e-49bb-9b13-3ee9da988d7a.png)

 

## Missing
- **County**
- **Base and Meridian:** this is determined by the first two numbers after the UT in BLM Point Name (e.g. UT**26**0410S0210E0_600200)
    - 26 = Salt Lake 
    - 30 = Uintah
 
![image](https://user-images.githubusercontent.com/15659642/203438677-d28da966-9133-447d-8712-4cb37b8fd87b.png)

- **Uploaded images**

![image](https://user-images.githubusercontent.com/15659642/203439781-5c6ed24f-ecea-4748-9ee8-0f79e79aa19c.png)

**Comment by steveoh** [comment]
> * Put the `Accuracy` data at the top of the Monument Description, followed by a carriage return, then the entered text starting on the next line

FYI, This will affect the amount of text the field can hold and still stay on one line.

**Comment by steveoh** [comment]
I'm going to call this done without the image stuff since you also have #182. This is duplicating that right?

**Comment by nathankota** [comment]
> I'm going to call this done without the image stuff since you also have #182. This is duplicating that right?

Yes, the images part is a duplicate of #182. Stuck on the validation of this until MR sheet preview is resolved; also mentioned in 182.

**Comment by nathankota** [comment]
validated
