### ISSUE TITLE
Request Google group to receive monument submission emails

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#164]
### [Service Now Form](https://utah.service-now.com/nav_to.do?uri=%2Fcom.glideapp.servicecatalog_cat_item_view.do%3Fv%3D1%26sysparm_id%3D35684a221b13ac10f22d0d84604bcb46%26sysparm_link_parent%3D9987742a1b536c10f22d0d84604bcb96%26sysparm_catalog%3De0d08b13c3330100c8b837659bba8fb4%26sysparm_catalog_view%3Dcatalog_default%26sysparm_view%3Dcatalog_default%2520target%26%2361;%26%2334;_self%26%2334;)

**Group Name:** 

**Group Email Address:** 

**Group Owner:** Sean

**Comment by steveoh** [comment]
## Suggtion

Name: UGRC PLSS Administrators
Email: ugrc-plss-administrators@utah.gov

It will need to allow emails from mail outside of the state of utah.

**Comment by nathankota** [comment]
> It will need to allow emails from mail outside of the state of utah.

If this is the group that receives the submissions first, isn't it just UGRC staff? Then once it is approved internally it gets sent to the county group, with non-state emails?

**Comment by steveoh** [comment]
The source of the email will be from the external email service SendGrid

**Comment by nathankota** [comment]
[RITM0222549](https://utah.service-now.com/sc_req_item.do?sys_id=15dac5c887e3d95002637489cebb3523&sysparm_record_target=sc_req_item&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog)

**Comment by nathankota** [comment]
![image](https://user-images.githubusercontent.com/15659642/204400957-123177e8-d7cd-4af8-948c-63f1ec4e2776.png)
