### ISSUE TITLE
Add section for Monument Submissions to My Content

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#165]
### [Something like this](https://miro.com/app/board/o9J_kmEqLOw=/?moveToWidget=3458764539481791812&cot=10)

- Above the Points section
- Both Points and Monument Submissions sections can expand and collapse
- Includes the following monument record info:
    - BLM point ID
    - Submitted date
    - Status timeline
- Includes the following tools
    - Zoom to entered coordinates, or BLM point if no coords entered for existing sheet
    - Download monument record sheet
    - Cancel submission if record status is Received

**Comment by steveoh** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/325813/204412926-de87fa0a-eab2-43b1-af03-63755b1c301d.png">

**Comment by steveoh** [comment]
I assigned this for testing the UI. None of the buttons work yet.

**Comment by nathankota** [comment]
this is perfect...future requests/needs will be included in new issues/tasks
