### ISSUE TITLE
TRS tool in the PLSS App not working

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#17]
Seems like the Township Range Section tool (TRS) doesn't work right now. 
You can enter a number and it seems to want to go back to the first one in the list, but if you type it twice it will go to what you typed and then give you and error. Same if you select from the list you get the error that is attached. This is the most pressing issue right now.
![plss_apperror](https://user-images.githubusercontent.com/10677659/38565700-364de94a-3c9f-11e8-8d88-d6cc09527e80.JPG)

Also tried to use the 'Find Place' tool, it just sits and spins, goes no where, did work before.
Find Coordinate works, 
The Tie Sheet Info tool keep giving a "550 Failed to change directory" error if you try to pull up a know tie sheet. Zoom never really worked, never got complaints either.

**Comment by mheagin** [comment]
Looks good thanks

**Comment by seanfernandez** [comment]
Gracias Amigo!
