### ISSUE TITLE
Surveyor seal image preview doesn't change

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#175]
- upload and save surveyor seal image
- exit profile, then go back into profile
- click Remove
- click Choose File, and upload new image
- the originally-uploaded image appears in the preview (I haven't tested yet whether the proper image appears on a "new" tiesheet)

**Comment by steveoh** [comment]
no actual images are used in the tiesheets yet

**Comment by steveoh** [comment]
this is a bit of a head scratcher. I'm going to side line it a bit to make some progress on some other items. Hopefully it's a not so common use case that won't give too many people an issue.

**Comment by steveoh** [comment]
this looks like a duplicate of #151 also

**Comment by nathankota** [comment]
added this info to #151 and closing
