### ISSUE TITLE
Show review page from the top by default

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#177]
Seems like the view of the Corner Submission Review page starts in the middle of the scrollable page when a lot of content is added, such as description verbiage, images, and extra pages. Have the review page start at the top (scrolled all the way up) by default, so the user can scroll down themselves to see all the content.

**Comment by steveoh** [comment]
I think it starts where you left it. I think I can reset that on transitions.

**Comment by nathankota** [comment]
For shites and giggles I started a submission from scratch and it went to the center-ish of the scroll on transition. No matter, sounds like you're on it. 🙏 

![image](https://user-images.githubusercontent.com/15659642/207915323-ab272627-bea0-49f3-abde-b25a4918b813.png)

**Comment by steveoh** [comment]
Right, were you scrolled down about that far on the images page when you clicked next?

**Comment by nathankota** [comment]
> Right, were you scrolled down about that far on the images page when you clicked next?

Ah, I'm following you now...the location of the previous page, duh. I'll check it out again shortly.

**Comment by steveoh** [comment]
This was an issue with all the pages including the home page and identify. It should be corrected now.

**Comment by nathankota** [comment]
looks good!
