### ISSUE TITLE
County Review email is directing them to invalid link address.

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#18]
When a Tie sheet is submitted and goes through our process from the PLSS Corner Management page (https://plss.utah.gov/ ) sends a follow up email to the county recorder or surveyor. This email has an invalid link.
"A monument record sheet in Juab has been submitted to the PLSS corner management portal by Riley Adams. Please review it here: http://mapserv.utah.gov/PLSS/TieSheet/review/811AB470-8AC7-4955-B187-33A0396C27DF and "reply all" to this email with your approval or with your reasons for not approving the sheet. If we do not hear from you within 10 days, we will consider the sheet approved and make it availabe on the portal. "
When you click on it now it gives a 404 error, 
Is this due to the httpS update a while back?

**Comment by steveoh** [comment]
No, the url should be plss.utah.gov instead of mapserv.utah.gov/plss

**Comment by steveoh** [comment]
@MichaelAGRC can you check to see if there is any reference `http://mapserv.utah.gov/PLSS/*` in the PLSS db and update it to `https://plss.utah.gov/*`. I think there might be a db mail function or something?

**Comment by MichaelAGRC** [comment]
Change has been made.  Please test and advise.

**Comment by mheagin** [comment]
The email now has an updated link -  https://plss.utah.gov/PLSS/TieSheet/review/A5A36E49-9B56-455F-930E-C8AAB0C817DC
but still getting 404 error
Remove the /PLSS please

**Comment by steveoh** [comment]
I removed the missed bit.
