### ISSUE TITLE
Include images, surveyor seal, extra pages in monument record sheet

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#182]
Just a reminder issue since I don't think we have one for it, even though we're aware that it needs to happen.

![image](https://user-images.githubusercontent.com/15659642/207920198-315483de-4edc-4e44-ac3a-6179bcab093d.png)

**Comment by steveoh** [comment]
@nathankota The commit above makes the front page complete i believe. Will you play with that?

**Comment by nathankota** [comment]
@steveoh I've made it to the review page a few times, but the MR sheet preview is not loading.

**Comment by steveoh** [comment]
Yep, my streams weren't ending. Check it again.

**Comment by nathankota** [comment]
The preview is loading and the images are included. Other things found during testing will be included in new issues.
