### ISSUE TITLE
Minor submission notification verbiage change

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#184]
Change is in italics/quote below. Want to emphasize first that the monument record sheet will show up in the site; then the point data update will occur, without specifying when.

### Submission success
What happens next?

The PLSS team at UGRC has been notified of your submission. They will review the submission and approve the sheet if there are no errors.

Next, UGRC will share the approved sheet with the representative from the county the monument is located in. The county representative will then review the submission and approve the sheet if there are no errors. They are provided 10 days to comment and after that time period they implicitly approve the sheet.

> _Once the sheet is approved, the monument record sheet pdf will be accessible through this PLSS website. UGRC will then use the submitted coordinates to improve the PLSS point dataset and fabric._ 

### Tracking progress
You can track the progress of this submission and all of your prior submissions by clicking on the **_My Content_** menu link.

**Comment by steveoh** [comment]
This would be a great chance to submit a pr ;)

**Comment by nathankota** [comment]
ref #186

**Comment by nathankota** [comment]
validated
