### ISSUE TITLE
Add Collection Date for all "new" submissions

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#185]
### Add a field in the new sheet submission workflow 
- **Field Name:** Collection Date 
- **Location:** Monument Metadata page, Collection section (section 3), above Accuracy
- **Field tip/text:** Date monument was surveyed
- **Field behavior:** Click field to select date from calendar, or key in date that adheres to calendar format
- **Validation:** Date must be on or before today's date (and adhere to calendar format)
- **Error messages:** 
    - If field is empty: _Collection Date is a required field._
    - If keyed-in date is incomplete or beyond today's date: _Collection Date must be on or before today's date._

### Additionally:
- Collection Date will need to show up on the submission review page, and
- Included on the monument record sheets that are created by the app:

![image](https://user-images.githubusercontent.com/15659642/209015885-ed507b13-87dd-41c6-8715-668a9899a9c8.png)

**Comment by steveoh** [comment]
You know the drill. Validation rules and error messages please.

**Comment by nathankota** [comment]
busted! forthcoming

**Comment by nathankota** [comment]
Initial issue information updated to include rules, error messages, etc. Please let me know if more information is needed.

**Comment by nathankota** [comment]
validated!
