### ISSUE TITLE
Allow three significant digits for the Elevation value

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#198]
- Location Information page for Grid coordinates entry
- Allow three decimal places to be entered for the Elevation value

![image](https://user-images.githubusercontent.com/15659642/210902167-13903ac1-16ff-452b-9b50-48722cf8ad7b.png)

**Comment by steveoh** [comment]
@nathankota Would this be for grid and geographic elevation or just this one specifically?

**Comment by nathankota** [comment]
> @nathankota Would this be for grid and geographic elevation or just this one specifically?

@seanfernandez and I only chatted about the grid elevation specifically. I better check with him again.

**Comment by steveoh** [comment]
geographic allows it. i checked

**Comment by nathankota** [comment]
worked in dev to add significant digits, but couldn't get through the submission process to ensure they were appearing on the review page, monument sheet, etc. No matter, though, because it all checks out in prod.
