### ISSUE TITLE
Submission email

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#199]
When a monument record is submitted,

Send email to:
- ugrc-plss-administrators@utah.gov
- ~county contact from [this sheet](https://docs.google.com/spreadsheets/d/1O4R8mOZmaNOGHxbDqYC5Ole_upMi4awMdBscNCH5sWE/edit#gid=0)~ (this will come later)

Subject line:
New PLSS Monument Record Submission

Body:
A new PLSS monument record has been submitted for [BLM Point ID].

A link in the email to the recipient's admin page, whether UGRC admin (#171) or county rep (#172).

Attachment:
The monument record sheet that was either uploaded, or created through the app.

**Comment by nathankota** [comment]
@seanfernandez Please take a look and let us know if anything needs to be different about the email subject, body, etc.

**Comment by nathankota** [comment]
Will eventually need a link in the email to the recipient's admin page, whether UGRC admin (#171) or county rep (#172).

**Comment by steveoh** [comment]
Here's the email preview. I wrote a script to add the email contacts to firebase. We can build the ui to manage that in the app later to replace the spreadsheet disconnect.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/325813/212208929-07f1cd6d-626b-45f4-9307-88c53c5174ce.png">

This was submitted in beaver so it picked up and added the beaver contact

<img width="382" alt="image" src="https://user-images.githubusercontent.com/325813/212208998-a15b147d-0e58-459f-9fd9-b7946b36f289.png">

I haven't added the attachment yet or the links to the review yet but will do that when it makes sense.

Currently, this email is triggered when the submission is written to the database. At that point the final sheet may not exist. 

If it's a new sheet it needs to be regenerated without the watermark and stored somewhere. It would make sense to trigger the email send after the final pdf is written to its storage location so it can be attached. 

If it's an existing monument submission, then the assets they submitted would need to be moved to the same place as the new submission so the same trigger runs to send the email notification.

**Comment by steveoh** [comment]
This is missing the api key and will not send mail at the moment.

**Comment by steveoh** [comment]
I fixed the api key issue yesterday and you should be able to test.

**Comment by nathankota** [comment]
Preview looks good. We determined to remove the county contact from the email in the app's initial release, and incorporate the tie sheet doc without the draft watermark.

**Comment by nathankota** [comment]
I'm not yet added to the group to receive emails, but based on how this looks (great) in the plss admin google group conversations, I'm going to validate and close this. I will check in with Sean too and, as always, if something is awry will create a new issue.
