### ISSUE TITLE
To-production tasks

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#200]
- [x] GCP prod project (@steveoh, [ut-dts-agrc-plss-prod](https://console.cloud.google.com/functions/list?project=ut-dts-agrc-plss-prod)) 
     - move monument record sheets to cloud storage
- [x] Archer package (@nathankota, @steveoh) ([diagrams](https://lucid.app/lucidchart/33071b1c-dcbb-42da-a050-51832e4a2636/edit?invitationId=inv_7eb44e28-8feb-47a6-80ff-f1dcbaff39d4&page=0_0#), [INC1766092](https://utah.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=a8d035948798a11402637489cebb35b4%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true), [Final Archer Package](https://utah.archer.rsa.com/default.aspx?requestUrl=..%2fGenericContent%2fRecord.aspx%3fid%3d464734%26moduleId%3d494))
    - update diagrams to include? 
        - firebase web sdk to talk directly to storage and firestore (diagram might be close enough)
        - api.mapserv for trs stuff
        - agol for points
        - discover for tiles 
- [x] GCP domain exceptions (@nathankota, @steveoh, [INC1767433](https://utah.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Dc50dad6d8794ed1402637489cebb35bc%26sysparm_stack%3Dincident_list.do%3Fsysparm_query%3Dactive%3Dtrue))
   - [allow unauthenticated](https://console.cloud.google.com/functions/list?project=ut-dts-agrc-plss-dev) is an exception (need prod gcp project first?)
   - add to the [UGRC exceptions list](https://docs.google.com/spreadsheets/d/1XyyZQYzkgrx-lJuOTgTnR7x6J2sXvZw8q6olBAwOO4M/edit#gid=0)

**Comment by steveoh** [comment]
#196 has the dns already fyi

**Comment by nathankota** [comment]
@steveoh are you able to verify that the domain restricted sharing policy has been disabled for the gcp project or are we okay to accept the resolution of [INC1767433](https://utah.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Dc50dad6d8794ed1402637489cebb35bc%26sysparm_stack%3Dincident_list.do%3Fsysparm_query%3Dactive%3Dtrue) and close this issue?

**Comment by steveoh** [comment]
I'm not sure how to verify until I try it. I think we can trust ops especially if we have securities blessing. then anyone of them will turn it off without issue.
