### ISSUE TITLE
empty Range list on TRS search tool

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#201]
- Select Township (for either Salt Lake or Uinta Basin)
- the Range list is always empty

![image](https://user-images.githubusercontent.com/15659642/211065929-6a0f39ea-45cf-4d1f-acc4-885737dedc44.png)

**Comment by steveoh** [comment]
Is it a bad api key? Did you look at the console or network tab?

**Comment by nathankota** [comment]
![image](https://user-images.githubusercontent.com/15659642/211360727-2d7751d4-1c89-4e28-be00-2ff5ea637986.png)

**Comment by steveoh** [comment]
apikey=undefined

**Comment by nathankota** [comment]
This is working. New issues/tasks will created as necessary from the results of more in depth testing.
