### ISSUE TITLE
TRS search error

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#202]
The following error occurs when searching/zooming to:

| Meridian | Township | Range | Section |
| ---------- | ---------- | ------- | -------- |
| Salt Lake | 28.5S | 18E | 29 |
| Salt Lake | 37.5S | 14W | 31 |

(will add more if/as they are discovered)

![image](https://user-images.githubusercontent.com/15659642/211399749-b5914010-9a68-4601-94ae-1fc3218ef12b.png)

**Comment by nathankota** [comment]
looks like the first TRS combo in the list can be found in the current/old app, but the second one just spins with no console error.

**Comment by nathankota** [comment]
Added low priority label.

What Section data set is used for the TRS search? In internal sgid and the fabric, there is only one record for 

Township | Range | Section
-- | -- | --
 28.5S | 18E | 29

However, in [open data](https://opendata.gis.utah.gov/datasets/utah-plss-sections-gcdb/explore?location=38.338767%2C-109.959614%2C-1.00), although the following have different FRSTDIVIDs, they have the same TOWNSHIP, RANGE, SECTION, BASEMERIDIAN, LABEL values...

Actual 28.5S, 18E, 29
![image](https://user-images.githubusercontent.com/15659642/211428947-96c37b83-9327-4618-acbc-541deeef22d8.png)

Should be 28S, 18E, 29
![image](https://user-images.githubusercontent.com/15659642/211429167-485d7421-b8a3-49ca-b60f-344cba34b9a8.png)

**Comment by steveoh** [comment]
I'm using `cadastre.plss_sections_gcdb`

**Comment by steveoh** [comment]
Turns out there are 465 duplicate labels with some having as many as 7 occurrences. 

```sql
select
	concat(basemeridian, "label", "section") as not_unique,
	count(*)
from
	cadastre.plss_sections_gcdb
group by
	concat(basemeridian, "label", "section")
having
	count(*) > 1
order by
	count desc
```

**Comment by nathankota** [comment]
This message is perfect. The root issue is related to the data. Closing.
 
![image](https://user-images.githubusercontent.com/15659642/213031830-14a5169b-fb77-4c8c-9259-8fb413d6e752.png)
