### ISSUE TITLE
Enable cancel button on my content

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#210]
- Click `Cancel` on Submissions page
- Confirmation notification and selection:
   _Are you sure you want to cancel this monument record submission?_ Y/N
- If No, notification goes away and nothing changes
- If Yes, 
    - The record is removed from the Submissions UI
    - The monument record pdf and any supporting images and files associated with this particular record are removed from cloud storage 
    - The record is removed from the app database

![image](https://user-images.githubusercontent.com/15659642/211938354-e4da3a2e-fc39-49ef-b684-0fd8d14e4481.png)

**Comment by steveoh** [comment]
This is wired up. 

Caveats

1. There is no confirmation dialog safety right now
1. The data is deleted. only marked as deleted
1. All the supporting data is deleted 
2. The final pdf doc is kept
3.  An email is sent to UGRC

**Comment by nathankota** [comment]
Validated in prod. Caveats above to be addressed later via #237
