### ISSUE TITLE
Links for “County Managed” pages need updating

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#22]
For the “County Managed” links for Tie Sheet Points we need to update at least Salt Lake and Utah
Salt Lake Co.
https://slco.org/surveyor/apps/surveymonument/map.html
Utah Co.
https://maps.utahcounty.gov/TieSheets/TieSheet.htm
Weber and Davis seem ok. Do you know of others? I thought Carbon but those are ours now.

**Comment by steveoh** [comment]
Isn't this stored in the data?

**Comment by steveoh** [comment]
https://github.com/agrc/PLSS/blob/master/PLSS/src/app/data/existingPlssWebsitesByCounty.js so this needs to be updated?

**Comment by mheagin** [comment]
Checked that database couldn't find anything............
That is what we needed....  let me check those others and see if any more are bad

**Comment by mheagin** [comment]
San Juan remove them, it will be ours

Uintah - http://www.co.uintah.ut.us/surveyor/UCTieSheet.htm

Wasatch - http://wasatch.maps.arcgis.com/apps/webappviewer/index.html?id=103db0251a5342f7bbd1462eb7a47440

these Salt lake and Utah I sent, the others are ok

**Comment by steveoh** [comment]
```js
define({
    'UTAH': 'https://maps.utahcounty.gov/TieSheets/TieSheet.htm',
    'WASATCH': 'https://wasatch.maps.arcgis.com/apps/webappviewer/index.html?id=103db0251a5342f7bbd1462eb7a47440',
    'DAVIS': 'http://www.co.davis.ut.us/surveyor/default.cfm',
    'SALT LAKE': 'https://slco.org/surveyor/apps/surveymonument/map.html',
    'WEBER': 'https://www.co.weber.ut.us/gis/maps/gizmo/',
    'DUCHESNE': 'https://duchesne.utah.gov/surveyor/base&meridian.html',
    'UINTAH': 'https://www.co.uintah.ut.us/surveyor/UCTieSheet.htm',
});
```

Double check this one more time before I update it please.

**Comment by mheagin** [comment]
That looks good everything checks.

**Comment by steveoh** [comment]
@mheagin it looks like `tiesheet_name` is null in a lot of the `plsspoint_agrc` feature class. If I remember correctly, if there was no tiesheet and the tiesheet was managed by one of the 7 counties above we put the county name in that field to tell the app to use the website.

I think a lot of points need that field be updated to make the website feature work properly. 

Thoughts?

**Comment by mheagin** [comment]
Well..... Salt Lake and Utah Co are not hitting the url from the table above so they are not working.
'UTAH': 'https://maps.utahcounty.gov/TieSheets/TieSheet.htm',
'SALT LAKE': 'https://slco.org/surveyor/apps/surveymonument/map.html',
And the points are acting weird, in those 7 counties, I am not seeing any of the orange ones that don't have tie sheets, everything goes purple. So I thought they were symbolized by the attribute DISPLAY_GRP, or are they influenced by the TieSheet_Name field?

**Comment by steveoh** [comment]
Did you spell salt lake and utah all caps and two words? They need to match exactly. 

I'll have to check the mxd for the symbology. You could also ask Scott. im pretty sure you made it and might have a copy also???

**Comment by mheagin** [comment]
Double checked the county names, they are correct. 

The symbology is set to TieSheet_Name, so that is where the issue is.
I'll talk to Sean and see what he want to do.

**Comment by mheagin** [comment]
wait ....so I cleared my cache and now the links work.
not sure why the new ones did work but the old ones didn't or did you change something?
Sean said to leave the point as they were.
So I think we are good now.
