### ISSUE TITLE
Change email recipient for Beaver Co, in App

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#3]
Please check and see who the recipient for Beaver Co. is, when the review emails are sent out for new submitted Tie Sheets.
It should be Beaver County Recorder 
Cindy Peterson 
crpeterson@beaver.utah.gov
Thanks

**Comment by steveoh** [comment]
I think this is stored in a database. Michael should be able to make it happen.

**Comment by mheagin** [comment]
I will check in with Michael when he gets in. Thanks

**Comment by mheagin** [comment]
The change has been made. Everything is up to date, as far as we know.
