### ISSUE TITLE
fix: Error fields and PLSS Id field are not populating when a point is selected

### ISSUE THREAD

**Issue by eneemann** [agrc/PLSS#34]
The following fields are not being populated when a point is selected:
- Error North
- Error East
- PLSS Id

We need to make sure these fields are wired up correctly, so all of the data is populated.

![image](https://user-images.githubusercontent.com/38330621/71114710-a032a380-218d-11ea-8218-8adfe13cebc3.png)

**Comment by steveoh** [comment]
Did you modify the field aliases when you updated the layers?

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/71114985-32d34280-218e-11ea-907c-ce8e0dea8a08.png)

is the current identify results. 

The app is looking for `PLSS Area Identification`,`Error in X`, and `Error in Y`

https://github.com/agrc/PLSS/blob/master/PLSS/src/app/templates/IdentifyTemplate.html

**Comment by eneemann** [comment]
I had to recreate these fields when building Point_AGRC from Point_GCDB because they had different field types.  However, I did not add an alias.  So the code relies on the alias and not the primary field name?

**Comment by steveoh** [comment]
Yes, the identify returns an alias if it has one so we'll need to update the mxd and republish

**Comment by eneemann** [comment]
I can just update my code to change the aliases in the data back to how they're expected.

**Comment by eneemann** [comment]
@steveoh made changes to the application code to handle the data as currently constructed.  Closing the issue.
![image](https://user-images.githubusercontent.com/38330621/71126030-5f468900-21a5-11ea-9647-26f625fd4d96.png)
