### ISSUE TITLE
enhancement: Add Cache county as an externally-linked website

### ISSUE THREAD

**Issue by eneemann** [agrc/PLSS#35]
Sean found a website for Cache county that can be linked to for points within the county:
http://66.232.67.238/websites/surveyviewer/ 

We need to add this to the web pages dictionary so it can be used as a link.

Note: The data will need to be populated in SGID's 'PLSSPoint_AGRC' layer before this enhancement would have any effect.

**Comment by steveoh** [comment]
Do you want to create a draft PR that we can make ready when the data is ready?

**Comment by eneemann** [comment]
Yeah, I can put that together.

**Comment by eneemann** [comment]
This was resolved with the implementation of PR #36
