### ISSUE TITLE
PLSS App does not draw correctly, the AGRC Point part of it.

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#4]
At first we lost the AGRC corner points when the update failed, we got that fixed so they do show up.
Now there is a issue with how they are drawing. You can zoom in and points are visible, up to I think a little less than 1:24,000 ( "Shot1" shows 9 to 12 sections depending on screen). If you click in or scroll in once more the points are gone ("zoom1" around 1:10,000, view a little more than 2 sections), and any where less than that they are no longer visible .
The mxd is setup for the AGRC Point which is a separate layer of the app that shows the corner points. They have four different scale dependent features setup with just the points that have tie sheet coming in first (purple dots). This happens down to 1:100,000 where the point size stays at 9 pts,. When your in below 1:40,000 the rest of the corners (orange dots) show up.
Neither of these features are set with a Max Scale, so they should draw no matter how far zoomed in you are. In the past they would show up even when the basemap was no longer drawing.
Thoughts:
Draw in the last two scale ranges are controlled by query from attribute "DISPLAY_GRP", second to the last attribute field, is it possible when it got copied this field was deleted somehow??

![shot1](https://cloud.githubusercontent.com/assets/10677659/10083085/1190422c-62ba-11e5-94ab-29c653e01116.JPG)
![zoom1](https://cloud.githubusercontent.com/assets/10677659/10083084/118d314a-62ba-11e5-9a7d-651b45aafd2a.JPG)

**Comment by steveoh** [comment]
I'm hoping this is sorted out now?

![image](https://cloud.githubusercontent.com/assets/325813/10140962/4313a0cc-65c7-11e5-9dd8-a4f2769fefec.png)

**Comment by mheagin** [comment]
Thanks Steve looks good now.

Mike

On Mon, Sep 28, 2015 at 9:57 AM, steveoh <notifications@github.com> wrote:

> Closed #4 <https://github.com/agrc/PLSS/issues/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/PLSS/issues/4#event-420908079>.
>



-- 
Mike Heagin
AGRC
gis.utah.gov
801-537-9296
