### ISSUE TITLE
Map Layers - Legend

### ISSUE THREAD

**Issue by nathankota** [agrc/PLSS#41]
### [Miro reference here](https://miro.com/app/board/o9J_kmEqLOw=/?moveToWidget=3074457350411260623&cot=12)
Map Layer feature contains a legend for the PLSS point layer, and reference layers. PLSS points are always on, reference layers can be turned on/off.

#### Remains the Same
- `County Managed`, `Monument Record`, `Calculated`, and `Control` remain same as current app
#### New

- `Pending` for submitted points/monument records (database changes TBD)
- Point cursor over legend item for pop-up description (to be provided by Cadastral Team)
- Triangle next to `Control` to indicate different symbology

![image](https://user-images.githubusercontent.com/15659642/104338718-0898a500-54b4-11eb-91a9-e2fc9eb16b4a.png)

**Comment by steveoh** [comment]
Is there a map service available with this symbology?

**Comment by mheagin** [comment]
That is the PLSSPoints_AGRC. It is not something we share publicly, so I don't think we have created a service, unless Erik has.

**Comment by steveoh** [comment]
The current plss app is using that data source now and is published as a map service on mapserv right? 

I'm requesting a pro project with the symbology, scale dependent rendering, yada yada and any new changes to support this legend request.

**Comment by mheagin** [comment]
Erik has been updating that lately, he may have created the service then.

**Comment by steveoh** [comment]
The last time I published the PLSS app service symbology changes I did work with Erik.

For this app, let's update that to an ArcGIS Pro project with any and all new things necessary for the app refresh.

**Comment by mheagin** [comment]
Sounds like Erik was using ArcMap to do the points updates for that app. He's out now so I will talk to him tomorrow
