### ISSUE TITLE
Map Layers - Reference Layers

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#42]
#### [Miro reference here](https://miro.com/app/board/o9J_kmEqLOw=/?moveToWidget=3074457350450343345&cot=12)
Map Layer feature contains a legend for the PLSS point layer, and reference layers. PLSS points are always on, reference layers can be turned on/off.

- [ ]  Landownership

- [ ] Parcels with Parcel ID as label

- [ ] BLM CadNSDI

  - All layers within the [version 2.2 database](https://gis.utah.gov/data/cadastre/plss/#CadNSDI)

  - Cadastral team to create map resource and define layer symbology

- Hover cursor on question mark for layer legend

![image](https://user-images.githubusercontent.com/15659642/98288819-a4fa7480-1f64-11eb-8e23-4a86772fdb99.png)

**Comment by steveoh** [comment]
this needs to be reworked some

**Comment by nathankota** [comment]
closed in favor of #77, #78, #79, #80
