### ISSUE TITLE
Users can no longer submit data for tie sheet.

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#5]
Got a call from a user saying they could not submit tie sheet today (filling in the form), said it worked two weeks ago.
I tried it this afternoon (June 20, 2016) and got the same thing, when you try to submit data it takes you to another front page the map, (http://mapserv.utah.gov/PLSS/#)
I also tried to submit existing sheet and got the same results.
When you are in the web app, it draws up slowly and never does draw up any points, is this causing the problem?
Also I checked the secure ftp site and we have had nothing submitted since Jan 29, 2016, so what ever they thought they submitted two weeks ago did not make it to the ftp site.
We have had 10 new users register this year, or at least that is the number of email notifications I have received.
I did see some dates on the submitted tables in the database PLSSADMIN.FormInfoes , for Douglas Grimshaw 6/8/2016, he was the one reporting that things were not working.

**Comment by steveoh** [comment]
This may have been caused by a bad database upgrade that we are just catching now. Will you or your users test this tomorrow with the changes dbase made today and see if it performs properly?

**Comment by mheagin** [comment]
Did some testing this morning. Submitted an existing sheet and it went through, and i got email notification.
Submitted corner data on form and nothing happened. Tried it again and hit the preview button it showed me the form, I downloaded it, looks fine. but no form showed up on the ftp site and no notification email.
I went and looked at the database tables and found the data entries for the points so something is missing between entry of data and the creation of the pdf and saving it for the ftp site.

**Comment by steveoh** [comment]
There seemed to be another loose end to tie up with the send mail stuff. @MichaelAGRC has been working with dbase and says it's time for another round of testing.

**Comment by mheagin** [comment]
Still the same I can preview what I enter into the sheet but once I submit it it is gone. Nothing in the ftp site and no email notification.

**Comment by steveoh** [comment]
Jeff Howard says, "Please try again"

**Comment by mheagin** [comment]
Tried it and got good results, pdf went through and I got the email notification.
Web sit is running again, drawing fast as before and looks good.
I notified our user down south and asked him to submit some tie sheet, they are out of the office til next week so, I will close this Issue now and if I hear back different from them we'll open a new one 
Thanks
