### ISSUE TITLE
Map Layers - Legend

### ISSUE THREAD

**Issue by nathankota** [agrc/PLSS#54]
### [Miro reference here](https://miro.com/app/board/o9J_kmEqLOw=/?moveToWidget=3074457352178447285&cot=14).

Mobile version of PLSS points legend. Tap "Map Layers" icon to expand. See miro link for functional details.

![image](https://user-images.githubusercontent.com/15659642/104346301-8365be00-54bc-11eb-9cdd-982a4ae299b7.png)

**Comment by steveoh** [comment]
this should be reworked as the map layers pane idea has changed
