### ISSUE TITLE
Map Layers - Reference Layers

### ISSUE THREAD

**Issue by nathankota** [agrc/PLSS#55]
### [Miro reference](https://miro.com/app/board/o9J_kmEqLOw=/?moveToWidget=3074457352178628159&cot=14) 

- Tap `Reference Layers` text within Map Layer panel to see available layers
- Tap to turn layer(s) on/off
- Tap `?` for reference layer legend (TBD for BLM CadNSDI)
- Same layers as desktop
- Active layers highlighted

![image](https://user-images.githubusercontent.com/15659642/104367082-8c17bd80-54d7-11eb-8e99-a4df9967f49d.png)

**Comment by steveoh** [comment]
replaced by layer list
