### ISSUE TITLE
My Content

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#58]
### [Mobile mockup](https://miro.com/app/board/o9J_kmEqLOw=/?moveToWidget=3074457352214189006&cot=14)

As a logged in user, I would like a link/button to view, interact with and edit my saved points or "content".
- Sort ascending/descending by date created, name (alphabetical/numerical)
- Select to only see list of records for visible area of map 
    - List changes as map moves
- Click/tap record in list to center point on map and highlight it in list and on map
- View point details
- Edit/delete point
- Hide/unhide point on map

**Comment by steveoh** [comment]
I assigned this for testing the UI. None of the buttons work yet.

**Comment by nathankota** [comment]
This looks freakin' awesome. My only comment/question so far is how to show uploaded images for the Reference Points?

**Comment by nathankota** [comment]
This looks good to me on both mobile and desktop. I'm going to close it and create a new issue for the images, while recognizing that the buttons don't work yet.
