### ISSUE TITLE
Update to County Contacts

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#6]
Need to update the County Contact for Tooele Co.
Tooele
Jerry Houghton
JHoughton@co.tooele.ut.us

to replace Doug Kinsman, no longer the surveyor.
Thanks

**Comment by steveoh** [comment]
@MichaelAGRC can you take care of this in the plss database please?

**Comment by MichaelAGRC** [comment]
The contact for Tooele Co. has been updated.
