### ISSUE TITLE
Need to update the County Contact list

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#62]
We have to update the county contacts list in the PLSS Corner Management App, for who gets notices of Tie Sheets to review with in each county. Changes reflect newly elected Recorders, new names and emails in second half of table.
Is it possible to do two contacts for a county? If so we would like to make two contacts for Garfield, add the Recorder and keep Les.
And in Rich Co., add Jim Kaisermann who contracts to do their survey work.
The list can be found here:
https://docs.google.com/spreadsheets/d/17yCjolz6qvrjw9LHPvfzSu0R5iNTyuK-fmAeAp2yE2s/edit#gid=0
That is it thanks

**Comment by MichaelAGRC** [comment]
We can update the contact info in the lookup, but I don't think that multiple contacts are currently supported in the app.  This will need to be reviewed by a dev before any changes are made to the lookup table.

**Comment by mheagin** [comment]
Do you know how we can ask that question to Steve in here?

**Comment by stdavis** [comment]
👀 Don't worry, @steveoh is always watching ... 👀

**Comment by mheagin** [comment]
thanks I figured like Beetlejuice I just had to say it for him to appear

**Comment by steveoh** [comment]
I was thinking the db was sending mail but Michael is right and the app is actually sending the mail. It is coded to handle one person. There are two ways to handle this, edit the plss app and redeploy or have the counties set up a group account or however it could be with their email provider.

@mheagin thoughts? 

cc @nathankota

**Comment by mheagin** [comment]
I am going to say leave it as is for now, we'll let the counties handle how to share or forward the email. Go ahead and make the changes shown in Green on in the table
Thanks

**Comment by MichaelAGRC** [comment]
I see no green in that table?

**Comment by steveoh** [comment]
I updated the table.
