### ISSUE TITLE
Submit Option - Ellipsoid Height not allowing meters

### ISSUE THREAD

**Issue by seanfernandez** [agrc/plss#74]
![Ellipsoid Height](https://user-images.githubusercontent.com/9937422/175378603-51ae5fa6-a36e-4c0b-9dbd-8dcaf5914f60.JPG)

**Comment by steveoh** [comment]
@seanfernandez what are the limits be for the other units?

**Comment by steveoh** [comment]
@seanfernandez can you provide the limits?

**Comment by seanfernandez** [comment]
0-12,000 should work for both feet and meters

**Comment by nathankota** [comment]
Another bug for entering longitude degrees is keeping me from accessing the elevation field, but I'm confident this has been resolved in previous iterations.
