### ISSUE TITLE
Add land ownership transparency

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#79]
So underlying basemap and data are still visible when it is turned on.

**Comment by steveoh** [comment]
Would this be a fixed opacity?

**Comment by nathankota** [comment]
Yes, fixed is fine since it's a reference layer. Same opacity value as the WRI app.

**Comment by steveoh** [comment]
It'd be great to determine what those values are so we don't have to go hunting

**Comment by steveoh** [comment]
I believe this is an upstream issue with the layer selector and will be fixed next dependency update.

**Comment by nathankota** [comment]
Looks like this is good to go.
