### ISSUE TITLE
Township Range Section zoom tool does not function

### ISSUE THREAD

**Issue by mheagin** [agrc/PLSS#8]
Township Range Section zoom tool does not function in the PLSS Web app or the TRSZoom addin.
In both instances you can add a Township but there is no option for Range in the web app, and it does nothing. 
In the Addin for ArcMap same thing you can add a township but no option for Range, after entering the Township you get a .NET Framework message:
'Unhandled exception has occurred in a component in your application. If you Click Continue, the application will ignore this error and attempt to continue.

The given key was not present in the dictionary"

If you push "Continue" you can type in a Range but then it gives a message at the bottom "Error Querying PLSS Data!".
I have made the move to Arc10.4 don't know if it matters but since both have the same problem I though not.
Thanks

**Comment by steveoh** [comment]
fixed this in the web api. The fix should fix both of these issues.
