### ISSUE TITLE
Add basic instructions to empty submit monument panel

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#81]
If a user selects the submit monument icon (#76) before selecting a point, add some verbiage either in the panel or elsewhere in the view that prompts them to select a PLSS point to proceed with a monument submission. 

Monument submission buttons should not be activated, or do not "work" (i.e. advance to the next submission page) before a PLSS point is selected.

**Comment by steveoh** [comment]
The way the flow is now they have to start by clicking a point. This is a side effect of adding the submit button always? Whether the user is logged in or a point is selected?

**Comment by nathankota** [comment]
closed in favor of #89
