### ISSUE TITLE
Make Geographic coords the default

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#85]
Sounds like 90% of surveyors will submit geographic coordinates, so:

- Swap the position of the two selections and
- Make `Geographic` the default selection

![image](https://user-images.githubusercontent.com/15659642/188902578-ecfb9173-1b06-47f2-a66d-98de9ccecb3a.png)

**Comment by nathankota** [comment]
Defaulting to Geographic looks good. The other part of the request that is missing is:

> * Swap the position of the two selections 

> ![image](https://user-images.githubusercontent.com/15659642/188902578-ecfb9173-1b06-47f2-a66d-98de9ccecb3a.png)

**Comment by steveoh** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/325813/192816624-e098cb19-67bc-4167-90ee-7d48a27cfc51.png">

This is the default view.

**Comment by nathankota** [comment]
excellent
