### ISSUE TITLE
Only allow NAD83 coordinate entry!

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#86]
Sean would like to constrain the accepted coordinate systems for both Geographic and Grid to NAD83. By default the drop-down will populate with the associated NAD83 values (below), but there can also be a (disabled) selection for `NATRF2022` for both Grid and Geographic, which is the new coordinate system coming in 2025. 

### Geographic > NAD83 Geographic
![image](https://user-images.githubusercontent.com/15659642/188938426-759dd15f-97f9-4456-b7e0-1a31515d7290.png)

### Grid > NAD83 State Plane
![image](https://user-images.githubusercontent.com/15659642/188938505-2290a45c-0be3-4463-8394-f474bed87018.png)

**Comment by steveoh** [comment]
@nathankota this is also nebulous because you don't specify the values and only show state plane for nad 83 in images.

The drop downs for for grid have  2 other nad83 values. Should those also go away or will the final lists be?

geographic 

- NAD83 Geographic
- NATRF2022 (disabled)

grid 

- NAD83 State Plane
- NAD83 UTM Zone 12N
- NAD83 UTM Zone 11N
- NATRF2022 (disabled)

basically removing wgs84 geographic, nad27 geographic, and nad27 state plane.

**Comment by steveoh** [comment]
Dev has the new dropdown values but the coordinate parsing needs updating most likely so this is half finished. But check out the drop downs and verify that those are what you are after please.

**Comment by nathankota** [comment]
Apologies for the vagueness. The selections shown on the images are the only NAD83 selections to include for Geographic and Grid, respectively; plus the (unselectable) NATRF2022 option for both. Yes, the two other NAD83 Grid selections should go away. Dev is displaying the drop down selections properly.

**Comment by steveoh** [comment]
> Dev is displaying the drop down selections properly.

Does that mean this should be closed?

**Comment by nathankota** [comment]
> > Dev is displaying the drop down selections properly.
> 
> Does that mean this should be closed?

It's fine with me to close it based on the selections appearing as expected. However, I didn't know if you needed to keep it open to address the second part of your comment:

>  ...but the coordinate parsing needs updating most likely so this is half finished.

**Comment by steveoh** [comment]
I moved it to validate the next day after i sorted that out.

**Comment by nathankota** [comment]
validated
