### ISSUE TITLE
Add elevation selection for Grid Coordinates

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#87]
Change data field name to Elevation and allow user to select one of the following options, then key in the value:
- NAVD88
- NGVD29

![image](https://user-images.githubusercontent.com/15659642/188907929-ee14bd71-e17b-4ffb-8c3e-5345f277f5b3.png)

**Comment by steveoh** [comment]
So there would be two fields with the label of elevation? I'll call it vertical datum unless you say otherwise.

**Comment by nathankota** [comment]
> So there would be two fields with the label of elevation? I'll call one vertical datum unless you say otherwise.

Sean confirmed that calling one of them "vertical datum" sounds good.

**Comment by nathankota** [comment]
validated
