### ISSUE TITLE
Elevation validation

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#88]
- Elevation is _**not required**_ for Grid Coordinates
- However, if Elevation is entered the acceptable ranges are:

    - 600 - 4,300 meters (if horizontal units defined as meters)
    - 2,000 - 14,000 feet (if horizontal units defined as feet)

**Comment by steveoh** [comment]
I read the lowest point in utah is 2000 ft. Should we use that?

**Comment by nathankota** [comment]
> I read the lowest point in utah is 2000 ft. Should we use that?

Yes. Initial comment edited to match values in #95.

**Comment by nathankota** [comment]
looks good
