### ISSUE TITLE
Default ("Home") App View

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#89]
The default view for all users is to have the left panel open with the message below. 

If a user is not logged-in when they first arrive at the app they will only see the `login/register`, `home` ([#90](https://github.com/agrc/plss/issues/90)), and `map legend` icons. 
If a users is already logged in when they first arrive at the app they will also see the `add point` and `my content` icons, in addition to the ones above.

New message:
Zoom-in on the map and click a PLSS point to see more information or to submit a monument record. 

![image](https://user-images.githubusercontent.com/15659642/188932727-a7b17ed5-9bcc-43ef-8788-fc98b1640032.png)

**Comment by steveoh** [comment]
I took some liberties to make the welcome message a little more interesting. Let me know if you want any changes made or if you would rather only have 

> Zoom-in on the map and click a PLSS point to see more information or to submit a monument record.

**Comment by steveoh** [comment]
To have this screen be the default open screen you have to navigate directly to https://plss.dev.utah.gov/home. If that is an issue we can try to work out a better solution.

**Comment by seanfernandez** [comment]
Good job Steveoh! The welcome message looks great.

**Comment by nathankota** [comment]
I agree, this is great, thank you. 

> To have this screen be the default open screen you have to navigate directly to https://plss.dev.utah.gov/home. If that is an issue we can try to work out a better solution.

@steveoh Is there some sort of indicator/arrow that can appear on the default page that points at the Home icon with some text like "Click here to begin"?

**Comment by steveoh** [comment]
https://react-joyride.com/custom seems like a solution but I wouldn't want to bring in the whole library for one interaction. We could certainly take a hint from their work and create some attention grabbing animation?

**Comment by nathankota** [comment]
I'm going to close this one and open a new one for the attention-grabbing animation.
