### ISSUE TITLE
Add Home icon to ribbon

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#90]
Add an icon and the text "Home" above the `Map Legend` icon.
When clicked, it goes back to the default view (#89).

![image](https://user-images.githubusercontent.com/15659642/188935312-033761c9-5c68-4285-8288-938dacf625e1.png)

**Comment by steveoh** [comment]
I think this makes more sense to be at the top but I'll let you see if you like it where it is.

**Comment by nathankota** [comment]
> I think this makes more sense to be at the top but I'll let you see if you like it where it is.

Sean and I agree with you that it makes more sense at the top. I'll close this and add a new issue for that.
