### ISSUE TITLE
Auto-calc other coordinates during submission

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#91]
### For Geographic Coordinates:
- Submitter selects `Geographic' and NAD83 and completes steps 2-4
- Click `Next` (auto-calc activated here)
- Grid coordinates are [calculated and displayed](https://github.com/agrc/plss/issues/105): 
   - (editable) **State plane zone:** according to output spatial reference
   - (editable) **Horizontal units:** default to meters
   - (editable) **Northing:** according to the [Project service](https://mapserv.utah.gov/arcgis/rest/services/Geometry/GeometryServer/project) result
   - (editable) **Easting:** according to the [Project service](https://mapserv.utah.gov/arcgis/rest/services/Geometry/GeometryServer/project) result
   - (editable) **Vertical datum:** defaults to NAVD88
   - (editable) **Elevation:** Blank, but a value can be keyed-in
  
### For Grid Coordinates:
- Submitter selects `Grid` and NAD83 State Plane and completes the next page (steps 2-4)
- Click `Next` (auto-calc activated here)
- Geographic coordinates are[ calculated and displayed](https://github.com/agrc/plss/issues/105):
  - (editable) **Latitude:** DMS
  - (editable) **Longitude:** DMS
  - (editable) **Ellipsoidal height:** Blank, but a value can be keyed-in 

### For auto-calculated coords
 - if submitter edits any of the (editable) calculated fields it does not change the originally-entered coordinates
 - if submitter backs out and alters originally-entered coords or changes the coordinate type and enters data, auto-calc wins at the `Next` button click

**Comment by steveoh** [comment]
Is the ellipsoidal height 3 different units?

**Comment by seanfernandez** [comment]
meters only

**Comment by steveoh** [comment]
This is done at submission time in the database or do we show it to the submitter?

**Comment by nathankota** [comment]
It is shown to the submitter. 
> Grid coordinates are calculated and displayed

The submitter has the option to
- accept the calc'd coords and move on ('Next')
- edit/enter their own coords, or even delete the calc'd coords, and move on (see "(editable)" fields in initial comment)
    - except "(not editable) **Elevation**"

**Comment by nathankota** [comment]
Original comment edited, based on conversation on 9/29/2022

**Comment by nathankota** [comment]
blocked by #105

**Comment by seanfernandez** [comment]
https://drive.google.com/drive/folders/1mLmjz_Z962ChnQRdADpdMrjP-qNJhzot?usp=sharing
This folder contains a spreadsheet with the counties listed by state plane zone and contains a file with coordinates of a point in each state plane zone.
https://www.ngs.noaa.gov/web_services/ncat/index.shtml
This link is to the NGS coordinate conversion tool API and can possibly be used to perform our conversions.

**Comment by nathankota** [comment]
@seanfernandez Great info here, thank you. I'm going to move it over to #105 

> https://drive.google.com/drive/folders/1mLmjz_Z962ChnQRdADpdMrjP-qNJhzot?usp=sharing This folder contains a spreadsheet with the counties listed by state plane zone and contains a file with coordinates of a point in each state plane zone. https://www.ngs.noaa.gov/web_services/ncat/index.shtml This link is to the NGS coordinate conversion tool API and can possibly be used to perform our conversions.

**Comment by nathankota** [comment]
Ref: #105

**Comment by nathankota** [comment]
closed, and info merged with #105
