### ISSUE TITLE
Auto-calc Geographic when Grid coords are entered

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#92]
(The antithesis of #91)

- User enters state plane zone, horizontal units, NGS adjustment, northing, easting, elevation
- Click `Next`
- Geographic coordinates are calculated and displayed:
  - (editable) **Latitude:** DMS
  - `Next`
  - (editable) **Longitude:** DMS
  - `Next`
  - (editable) **Ellipsoidal height:** same elevation units (meters or feet) as what was entered for grid coords
  - `Next`
- Goes to image upload ([#93](https://github.com/agrc/plss/issues/93))

**Comment by steveoh** [comment]
same question for elevation. are we converting to meters

**Comment by seanfernandez** [comment]
elevation can be in either feet of meters, and honestly we can just call it feet rather than specifying us survey or international because the distance in feet for an elevation is small enough that it doesnt matter.

**Comment by nathankota** [comment]
@seanfernandez To try to answer Steve's question a bit more, if Grid coords are entered, we are only going to convert to the ellipsoidal height in meters for the calculated geographic coords. If the user wants to change it to feet, then can. Does that make sense and align with what you're thinking?

**Comment by nathankota** [comment]
@steveoh Are you asking, if the user enters elevation as feet when entering the grid coordinates, do we convert that elevation to meters before calculating the geographic coords?

**Comment by nathankota** [comment]
The elevation selection should stay the same as what was entered. If submitter enters elevation as feet when entering grid coordinates, the elevation should stay as feet when geographic coords are calculated.

**Comment by steveoh** [comment]
I think we need to think about how this works and is shown to the submitter. 

Right now, a submitter can go to geographic, enter all the data and then go back and switch to grid and enter all the points and submit. I thought we would calculate the other coordinates at submission time so when they go back and start to enter the grid coordinates, the geographic data is cleared out so the submission results have the accurate data and we can tell the difference between what was expected.

Now to reuse the same components and validation we already have built, the form will need to show the opposite coordinates after one type is keyed in and calculated so they can accept or edit them. 

Where it could get weird is when they go back to make a change to the original coordinates.

Do we auto calc the coordinates again and overwrite them? Do we leave them the same? I'm sure there are other scenarios i haven't thought of yet but I think I've explained some of the complexities that are not addressed by this issue. 

Think about these concerns and let me know what the submitter should expect so we can build the right form.

**Comment by nathankota** [comment]
Closed in favor of reworked #91
