### ISSUE TITLE
Add images and extra pages to monument submission

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#93]
After the coordinates are entered. 
Like the existing app where there are four sections:
- Map View Photo or Sketch (1 upload limit)
- Monument Area Photo (1 upload limit)
- Monument Close-up Photo (1 upload limit)
- Extra Pages (10 upload limit)

Accepted file types for all sections are: jpg, jpeg, png, tiff

- `Next` button to go to submission review, then
- `Submit` button appears on this page, as it is the last step in the submission process.

**Comment by steveoh** [comment]
So the review step I have is to be removed?

**Comment by nathankota** [comment]
> So the review step I have is to be removed?

No, I just forgot to include that. The review step is great. Initial comment updated.

**Comment by steveoh** [comment]
How many of these photos are required?

**Comment by nathankota** [comment]
None of the photos are required.

**Comment by steveoh** [comment]
I'd like to suggest that we only allow images and remove pdf's as inputs to this section.

**Comment by nathankota** [comment]
Confirmed with Sean that it is okay to remove pdf as an acceptable file type.

**Comment by nathankota** [comment]
This is great. Some changes will be requested in new tasks/issues, but this will be closed.
