### ISSUE TITLE
Monument form submission with existing sheet

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#94]
If user selects this option (#82):
- [ ] #109
- [x] `Next` button
- [x] Present option (not required) to enter geographic or grid coordinates, or `Next` to skip
  - [x] if they do enter coords, then calculate the other type of coords (#91), then `Next`
- [x] `Submit`

**Comment by steveoh** [comment]
One of the coordinates is required correct?

**Comment by nathankota** [comment]
> One of the coordinates is required correct?

Sean said they do not have to enter any coords here if they choose not to.

**Comment by steveoh** [comment]
This is partially complete. But i'd like you to check it out and create any issues you find.

**Comment by nathankota** [comment]
I'm going to close this issue and create new ones based on what is in the app now for this process.
