### ISSUE TITLE
Ellipsoid height validation

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#95]
- **Meters:** between 600 and 4,300
- **Feet:** between 2,000 and 14,000 (looks like this is already implemented, but it is also applied to meters currently)

![image](https://user-images.githubusercontent.com/15659642/188994626-e09d39f4-0f69-4738-8680-0d2fd5e31c8d.png)

**Comment by steveoh** [comment]
This contradicts #88. I think these values are better choices and will use them instead of what you suggested in 88.
