### ISSUE TITLE
Only need meters and feet selections for Ellipsoid Height

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#96]
Because the difference in distance between US Survey and International feet is so small, there only needs to be selections for meters and feet for Ellipsoid Height when entering Geographic coordinates.

![image](https://user-images.githubusercontent.com/15659642/189175334-4ecb19fa-1f1a-4f78-9178-a52d37a1eb9c.png)

**Comment by steveoh** [comment]
US Survey feet are used in 

- the ellipsoid height for geographic coordinates an,
- horizontal units in grid height

Should survey feet be removed from both areas?

**Comment by nathankota** [comment]
> Should survey feet be removed from both areas?

Yes, please. There should only be selections for "meters" and "feet" in both of those areas (ellipsoid height and horizontal units). Thank you for catching that.

**Comment by nathankota** [comment]
validated
