### ISSUE TITLE
legend descriptions

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#99]
We need a description for each of the PLSS point types for when a user clicks on the layers name:
(updated to show the addition of MRRC Monument Record, and the removal of Pending)

![image](https://user-images.githubusercontent.com/15659642/204607116-bbf9e539-14c4-4983-8845-79bbf8eadfe4.png)

**Comment by seanfernandez** [comment]
I'll put it on my schedule

**Comment by nathankota** [comment]
@seanfernandez reminder

**Comment by nathankota** [comment]
Also need one for the MRRC Monument Record (#116)

**Comment by steveoh** [comment]
https://github.com/agrc/plss/issues/168 removes pending

**Comment by eneemann** [comment]
- County Managed: PLSS points whose monument record sheets and information are managed on a county website.
- Monument Record: PLSS points with an available monument record sheet.
- Control: PLSS points that have been incorporated into the PLSS Fabric as control points.
- Calculated: PLSS points without monument record sheets whose location has been calculated from the PLSS Fabric and surrounding points.
- Pending: PLSS points that have a pending monument record sheet that is awaiting review/acceptance.

**Comment by nathankota** [comment]
@eneemann these look great, thank you. I updated the initial comment to show that we made some changes to the legend. MRRC Monument Record is a new one, and we are removing Pending. Can you please change your Pending description to a description for MRRC Monument Record?

**Comment by eneemann** [comment]
@nathankota I edited my response above ☝️

**Comment by nathankota** [comment]
validated
